version: "3.3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    image: dmitryburdukevich/webapp
    command: bash -c "
       python ./shop/manage.py makemigrations &&
       python ./shop/manage.py migrate &&
       python ./shop/manage.py loaddata ./shop/initial_data.json &&
       python ./shop/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
