# Generated by Django 3.1.7 on 2021-06-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210607_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemRewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='rewards',
            field=models.ManyToManyField(default='No awards', to='main.OrderItemRewards'),
        ),
    ]
