# Generated by Django 3.1.7 on 2021-06-08 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210608_0525'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItemRewards',
            new_name='ProductRewards',
        ),
    ]
