# Generated by Django 3.1.7 on 2021-06-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210608_0527'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductRewards',
            new_name='ProductReward',
        ),
    ]
